import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import SessionProviderWrapper from "@/utils/SessionProviderWrapper";
import AxiosConfig from "@/utils/AxiosConfig";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";

const roboto = Roboto({
  weight: ["100", "900"],
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // eslint-disable-next-line object-curly-newline
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable} antialiased`}>
        <Suspense fallback={<p>loading...</p>}>
          <SessionProviderWrapper>
            <AxiosConfig />
            <Toaster />
            {children}
          </SessionProviderWrapper>
        </Suspense>
      </body>
    </html>
  );
}
